extends: scala-github-actions

pull_request_rules:
  - name: flag non breaking changes
    conditions:
      - check-success~=^test / binary-compatibility
      - -check-pending~=^test / binary-compatibility
      - -check-failure~=^test / binary-compatibility
    actions:
      label:
        toggle:
          - non-breaking-change

  - name: flag binary incompatible changes
    conditions:
      - check-failure~=^test / binary-compatibility
    actions:
      label:
        toggle:
          - release-bump-needed
