queue_rules:
  - name: default
    merge_method: rebase
    update_method: rebase
    merge_conditions:
      - check-success~=^test /
      - -check-pending~=^test /
      - -check-failure~=^test /

pull_request_rules:
  - name: queue approved pull requests
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
    actions:
      queue:

  - name: queue scala-steward updates
    conditions:
      - base=master
      - author=scala-steward
      - label!=do-not-merge
    actions:
      queue:

  - name: rebase stale pull requests
    conditions:
      - base=master
      - -conflict
      - "#commits-behind>0"
    actions:
      update:
        method: rebase

